/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Collection {
  'id' : string,
  'coverImageId' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export interface NFT {
  'id' : string,
  'title' : string,
  'edition' : string,
  'collectionId' : string,
  'description' : string,
  'mintedAt' : bigint,
  'imageId' : ExternalBlob,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'burnNFT' : ActorMethod<[string], undefined>,
  'createCollection' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'deleteCollection' : ActorMethod<[string], undefined>,
  'getAllCollections' : ActorMethod<[], Array<Collection>>,
  'getAllNFTs' : ActorMethod<[], Array<NFT>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectionById' : ActorMethod<[string], Collection>,
  'getNFTById' : ActorMethod<[string], NFT>,
  'getNFTsByCollection' : ActorMethod<[string], Array<NFT>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintNFT' : ActorMethod<
    [string, string, string, ExternalBlob, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCollection' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateNFT' : ActorMethod<
    [string, string, string, ExternalBlob, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];